main_app/urls.py
from django.urls import path

from main_app.EditResultView import EditResultView

from . import hod_views, staff_views, booking_views, views

urlpatterns = [
    path("", views.landing_page, name="landing_page"),
    path("login/", views.login_page, name="login_page"),
    path("get_trips", views.get_trips, name='get_trips'),
    path("firebase-messaging-sw.js", views.showFirebaseJS, name='showFirebaseJS'),
    path("doLogin/", views.doLogin, name='user_login'),
    path("logout_user/", views.logout_user, name='user_logout'),
    path("admin/home/", hod_views.admin_home, name='admin_home'),
    path("staff/add", hod_views.add_staff, name='add_staff'),
    path("role/add", hod_views.add_role, name='add_role'),
    path("send_staff_notification/", hod_views.send_staff_notification,
         name='send_staff_notification'),
    path("add_Season/", hod_views.add_Season, name='add_Season'),
    path("admin_notify_staff", hod_views.admin_notify_staff,
         name='admin_notify_staff'),
    path("admin_view_profile", hod_views.admin_view_profile,
         name='admin_view_profile'),
    path("check_email_availability", hod_views.check_email_availability,
         name="check_email_availability"),
    path("Season/manage/", hod_views.manage_Season, name='manage_Season'),
    path("Season/edit/<int:Season_id>",
         hod_views.edit_Season, name='edit_Season'),
    path("booking/view/feedback/", hod_views.booking_feedback_message,
         name="booking_feedback_message",),
    path("staff/view/feedback/", hod_views.staff_feedback_message,
         name="staff_feedback_message",),
    path("staff/view/leave/", hod_views.view_staff_leave, name="view_staff_leave",),
    path("trips/fetch/", hod_views.get_admin_trips,
         name='get_admin_trips'),
    path("booking/add/", hod_views.add_booking, name='add_booking'),
    path("Car/add/", hod_views.add_Car, name='add_Car'),
    path("itinerary/add/", hod_views.add_itinerary, name='add_itinerary'),
    path("staff/manage/", hod_views.manage_staff, name='manage_staff'),
    path("booking/manage/", hod_views.manage_booking, name='manage_booking'),
    path("role/manage/", hod_views.manage_role, name='manage_role'),
    path("Car/manage/", hod_views.manage_Car, name='manage_Car'),
    path("itinerary/manage/", hod_views.manage_itinerary, name='manage_itinerary'),
    path("staff/edit/<int:staff_id>", hod_views.edit_staff, name='edit_staff'),
    path("staff/delete/<int:staff_id>",
         hod_views.delete_staff, name='delete_staff'),

    path("role/delete/<int:role_id>",
         hod_views.delete_role, name='delete_role'),

    path("Car/delete/<int:Car_id>",
         hod_views.delete_Car, name='delete_Car'),

    path("itinerary/delete/<int:itinerary_id>",
         hod_views.delete_itinerary, name='delete_itinerary'),

    path("Season/delete/<int:Season_id>",
         hod_views.delete_Season, name='delete_Season'),

    path("booking/delete/<int:booking_id>",
         hod_views.delete_booking, name='delete_booking'),
    path("booking/edit/<int:booking_id>",
         hod_views.edit_booking, name='edit_booking'),
    path("role/edit/<int:role_id>",
         hod_views.edit_role, name='edit_role'),
    path("itinerary/edit/<int:itinerary_id>",
         hod_views.edit_itinerary, name='edit_itinerary'),
    path("Car/edit/<int:Car_id>",
         hod_views.edit_Car, name='edit_Car'),




    # Staff
    path("staff/home/", staff_views.staff_home, name='staff_home'),
    path("staff/apply/leave/", staff_views.staff_apply_leave,
         name='staff_apply_leave'),
    path("staff/feedback/", staff_views.staff_feedback, name='staff_feedback'),
    path("staff/view/profile/", staff_views.staff_view_profile,
         name='staff_view_profile'),
    path("staff/trips/take/", staff_views.staff_take_trips,
         name='staff_take_trips'),
    path("staff/trips/update/", staff_views.staff_update_trips,
         name='staff_update_trips'),
    path("staff/get_bookings/", staff_views.get_bookings, name='get_bookings'),
    path("staff/trips/fetch/", staff_views.get_booking_trips,
         name='get_booking_trips'),
    path("staff/trips/save/",
         staff_views.save_trips, name='save_trips'),
    path("staff/trips/update/",
         staff_views.update_trips, name='update_trips'),
    path("staff/fcmtoken/", staff_views.staff_fcmtoken, name='staff_fcmtoken'),
    path("staff/view/notification/", staff_views.staff_view_notification,
         name="staff_view_notification"),
    path("staff/result/add/", staff_views.staff_add_result, name='staff_add_result'),
    path("staff/result/edit/", EditResultView.as_view(),
         name='edit_booking_result'),
    path('staff/result/fetch/', staff_views.fetch_booking_result,
         name='fetch_booking_result'),


    # booking
    path("booking/home/", booking_views.booking_home, name='booking_home'),
    path("booking/view/trips/", booking_views.booking_view_trips,
         name='booking_view_trips'),
    path("booking/apply/leave/", booking_views.booking_apply_leave,
         name='booking_apply_leave'),
    path("booking/feedback/", booking_views.booking_feedback,
         name='booking_feedback'),
    path("booking/view/profile/", booking_views.booking_view_profile,
         name='booking_view_profile'),
    path("booking/fcmtoken/", booking_views.booking_fcmtoken,
         name='booking_fcmtoken'),
    path("booking/view/notification/", booking_views.booking_view_notification,
         name="booking_view_notification"),
    path('booking/view/result/', booking_views.booking_view_result,
         name='booking_view_result'),

]

namelok_software_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("", include('main_app.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main_app/models.py
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import UserManager
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db import models
from django.contrib.auth.models import AbstractUser, User
# from networkx import cartesian_product
# from .tests import get_default_season, get_default_car
# from main_app.forms import CarForm
from main_app.tests import get_default_car, get_default_season
from namelok_software_system import settings

from django.contrib.auth import get_user_model
class CustomUserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = CustomUser(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        assert extra_fields["is_staff"]
        assert extra_fields["is_superuser"]
        return self._create_user(email, password, **extra_fields)


class Season(models.Model):
    name = models.CharField(max_length=120)
    start_year = models.DateField()
    end_year = models.DateField()

   

    def __str__(self):
        return "From " + str(self.start_year) + " to " + str(self.end_year)


class CustomUser(AbstractUser):
    USER_TYPE = ((1, "HOD"), (2, "Staff"), (3, "booking"))
    GENDER = [("M", "Male"), ("F", "Female")]
    
    username = None  # Removed username, using email instead
    email = models.EmailField(unique=True)
    user_type = models.CharField(default=1, choices=USER_TYPE, max_length=1)
    gender = models.CharField(max_length=1, choices=GENDER, default='M')  # Set default to 'Male'
    profile_pic = models.ImageField()
    address = models.TextField()
    fcm_token = models.TextField(default="")  # For firebase notifications
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

    def __str__(self):
        return self.last_name + ", " + self.first_name



class Admin(models.Model):
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)



class Role(models.Model):
    name = models.CharField(max_length=120)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class booking(models.Model):
    admin = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.DO_NOTHING, null=True, blank=True)
    season = models.ForeignKey(Season, on_delete=models.DO_NOTHING, null=True, blank=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='bookings', default=None)

    def __str__(self):
       return f"{self.user.last_name}, {self.user.first_name}"

class Staff(models.Model):
    name = models.CharField(max_length=255, default='Default Name')
    role = models.ForeignKey(Role, on_delete=models.DO_NOTHING, null=True, blank=False)
    admin = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.admin.last_name + " " + self.admin.first_name


class Car(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=120)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Itinerary(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=120)
    description = models.CharField(max_length=500)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name
    

class Trips(models.Model):
    season = models.ForeignKey(Season, on_delete=models.DO_NOTHING)
    car = models.ForeignKey(Car, on_delete=models.DO_NOTHING)
    date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class tripsReport(models.Model):
    booking = models.ForeignKey(booking, on_delete=models.DO_NOTHING)
    trips = models.ForeignKey(Trips, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class LeaveReportbooking(models.Model):
    booking = models.ForeignKey(booking, on_delete=models.CASCADE)
    date = models.CharField(max_length=60)
    message = models.TextField()
    status = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class LeaveReportStaff(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    date = models.CharField(max_length=60)
    message = models.TextField()
    status = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Feedbackbooking(models.Model):
    booking = models.ForeignKey(booking, on_delete=models.CASCADE)
    feedback = models.TextField()
    reply = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class FeedbackStaff(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    feedback = models.TextField()
    reply = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class NotificationStaff(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Notificationbooking(models.Model):
    booking = models.ForeignKey(booking, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class bookingResult(models.Model):
    booking = models.ForeignKey(booking, on_delete=models.CASCADE)
    Car = models.ForeignKey(Car, on_delete=models.CASCADE)
    test = models.FloatField(default=0)
    exam = models.FloatField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        if instance.user_type == 1:
            Admin.objects.create(admin=instance)
        elif instance.user_type == 2:
            # Assuming each CustomUser can have one Staff instance associated with it
            # Check if the CustomUser instance has an associated Staff instance
            staff_instance, _ = Staff.objects.get_or_create(admin=instance)
            staff_instance.name = f"{instance.last_name}, {instance.first_name}"
            staff_instance.save()
        elif instance.user_type == 3:
            booking.objects.create(admin=instance)


@receiver(post_save, sender=CustomUser)
def save_user_profile(sender, instance, **kwargs):
    if instance.user_type == 1:
        instance.admin.save()
    elif instance.user_type == 2:
        # Assuming each CustomUser can have one Staff instance associated with it
        # Check if the CustomUser instance has an associated Staff instance
        staff_instance, created = Staff.objects.get_or_create(admin=instance)
        # Save the Staff instance
        staff_instance.save()
    elif instance.user_type == 3:
        instance.booking.save()

main_app/templates/staff_template/edit_inquiry_result.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                    <form method="POST">
                        {% csrf_token %}
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

       
                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="card-body">


                     

                 {{ form }}

                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" id='update_result' class="btn btn-primary btn-block">Update Result</button>
               
                    </div>
                </form>
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}


{% block custom_js %}
<script>
    $(document).ready(function () {
        $("#id_Car").change(function () {
            fetchbookings();
            });
            $("#id_Season_year").change(function () {
                fetchbookings();
                });
   $("#id_booking").change(function () {
    fetch_booking_result();
                });
                $("#id_exam").hide()
                $("#id_test").hide()
                $("#update_result").hide()
                $('label[for="id_test"]').hide();
                $('label[for="id_exam"]').hide();
        function fetchbookings(){
            var Car = $("#id_Car").val()
            var Season = $("#id_Season_year").val()
            $("#id_booking").html(null)
            if (Season.length  == 0 || Car.length == 0 || Season < 1 || Car < 1){
                return false;
            }
            $.ajax({
                url: "{% url 'get_bookings' %}",
                type: 'POST',
                data: {
                    Car: Car,
                    Season:Season
                }
            }).done(function (response) {
                var json_data = JSON.parse(response)
                if (json_data.length < 1) {
                    alert("No data to display")
                } else {
                    var div_data = "<option>Select booking</option>"

                    for (key in json_data) {
                        div_data += "<option value='" + json_data[key]['id'] + "'>" + json_data[key]['name'] + " </option>"
                    }
             
                    $("#id_booking").html(div_data)
                }
            }).fail(function (response) {
                alert("Error in fetching bookings")
            })
               }

               function fetch_booking_result(){
                var booking = $("#id_booking").val()
                var Car = $("#id_Car").val()
                $("#id_test").val(null)
                $("#id_exam").val(null)
                $("#id_exam").hide()
                $("#update_result").hide()
                $("#id_test").hide()
                $('label[for="id_test"]').hide();
                $('label[for="id_exam"]').hide();
                if (booking.length  == 0 || Car.length == 0 || booking < 1 || Car < 1){
                    return false;
                }
                $.ajax({
                    url: "{% url 'fetch_booking_result' %}",
                    type: 'POST',
                    data: {
                        Car: Car,
                        booking:booking
                    }
                }).done(function (response) {
                    if (response == 'False') {
                        alert("No data to display")
                    } else {
                        var json_data = JSON.parse(response)
                        
                            $("#id_test").val(json_data['test'])
                            $("#id_exam").val(json_data['exam'])
                            $("#id_exam").show()
                            $("#id_test").show()
                            $("#update_result").show()
                            $('label[for="id_test"]').show();
                            $('label[for="id_exam"]').show();

                    }
                }).fail(function (response) {
                    alert("Error in fetching bookings")
                })
               }

    })
</script>
{% endblock custom_js %}

main_app/templates/staff_template/home_content.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block content %}
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-info">
                    <div class="inner">
                        <h3>{{total_bookings}}</h3>

                        <p>Total bookings</p>
                    </div>
                    <div class="icon">
                      <i class="nav-icon fas fa-user-graduate"></i>
                    </div>
                   
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-success">
                    <div class="inner">
                        <h3>{{total_trips}}</h3>

                        <p>Total trips Taken</p>
                    </div>
                    <div class="icon">
                      <i class="nav-icon fas fa-calendar-alt"></i>
                    </div>
                   
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-maroon">
                    <div class="inner">
                        <h3>{{total_leave}}</h3>

                        <p>Total Leave Applied</p>
                    </div>
                    <div class="icon">
                      <i class="nav-icon fas fa-sign-out-alt"></i>
                    </div>
                   
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-danger">
                    <div class="inner">
                        <h3>{{total_Car}}</h3>

                        <p>Total Cars</p>
                    </div>
                    <div class="icon">
                      <i class="nav-icon fas fa-book"></i>
                    </div>
                   
                </div>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <div class="row">
            <div class="col-md-6">
                <!-- LINE CHART -->
                <div class="card card-secondary">
                  <div class="card-header">
                    <h3 class="card-title">{{page_title}}</h3>
    
                    <div class="card-tools">
                      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                      </button>
                      <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                    </div>
                  </div>
                  <div class="card-body">
                    <div class="chart">
                      <canvas id="pieChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                    </div>
                  </div></div>
                  <!-- /.card-body -->
                </div>
                <div class="col-md-6">
                    <div class="card card-secondary">
              <div class="card-header">
                <h3 class="card-title">{{page_title}}</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                  </button>
                  <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                </div>
              </div>
              <div class="card-body">
                <div class="chart">
                  <canvas id="barChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                </div>
              </div>
              <!-- /.card-body -->
            </div>
                </div>
            <!-- right col -->
        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>
{% endblock content %}

{% block custom_js %}
  <script>
      $(document).ready(function(){
        var donutData        = {
            labels: ['trips', 'Leave'],
            datasets: [
              {
                data:[{{total_trips}}, {{total_leave}}],
                backgroundColor : ['#00a65a', '#f39c12',],
              }
            ]
          }
        var pieChartCanvas = $('#pieChart').get(0).getContext('2d')
        var pieData        = donutData;
        var pieOptions     = {
          maintainAspectRatio : false,
          responsive : true,
        }
        //Create pie or douhnut chart
        // You can switch between pie and douhnut using the method below.
        var pieChart = new Chart(pieChartCanvas, {
          type: 'pie',
          data: pieData,
          options: pieOptions      
        });

        var Car_list = {{ Car_list|safe|escape }};
        var trips_list = {{ trips_list }};
  
            var barChartData = {
      labels  : Car_list,
      datasets: [
      {
        label               : 'trips Per Car',
        backgroundColor     : '#17A2B8',
        borderColor         : 'rgba(60,141,188,0.8)',
        pointRadius          : false,
        pointColor          : '#3b8bba',
        pointStrokeColor    : 'rgba(60,141,188,1)',
        pointHighlightFill  : '#fff',
        pointHighlightStroke: 'rgba(60,141,188,1)',
        data                : trips_list
      }, 
      
      ]
    }
        var barChartCanvas = $('#barChart').get(0).getContext('2d')
        var temp0 = barChartData.datasets[0]
        //var temp1 = areaChartData.datasets[1]
        barChartData.datasets[0] = temp0
       // barChartData.datasets[1] = temp0
    
    var stackedBarChartOptions = {
      responsive              : true,
      maintainAspectRatio     : false,
      scales: {
        xAxes: [{
          stacked: true,
        }],
        yAxes: [{
          stacked: true
        }]
      }
    }
    
        var barChart = new Chart(barChartCanvas, {
          type: 'bar', 
          data: barChartData,
          options: stackedBarChartOptions
        })
      })

    
  </script>
      <!-- The core Firebase JS SDK is always required and must be listed first -->
      <script src="https://www.gstatic.com/firebasejs/7.23.0/firebase-app.js"></script>

      <!-- TODO: Add SDKs for Firebase products that you want to use
       https://firebase.google.com/docs/web/setup#available-libraries -->
      <script src="https://www.gstatic.com/firebasejs/7.23.0/firebase-analytics.js"></script>
      <script src="https://www.gstatic.com/firebasejs/7.22.1/firebase-messaging.js"></script>
  
  
      <script>
          // Your web app's Firebase configuration
          // For Firebase JS SDK v7.20.0 and later, measurementId is optional
          var firebaseConfig = {
              apiKey: "AIzaSyBarDWWHTfTMSrtc5Lj3Cdw5dEvjAkFwtM",
              authDomain: "sms-with-django.firebaseapp.com",
              databaseURL: "https://sms-with-django.firebaseio.com",
              projectId: "sms-with-django",
              storageBucket: "sms-with-django.appspot.com",
              messagingSenderId: "945324593139",
              appId: "1:945324593139:web:03fa99a8854bbd38420c86",
              measurementId: "G-2F2RXTL9GT"
          };
          // Initialize Firebase
          firebase.initializeApp(firebaseConfig)
          const messaging = firebase.messaging();
          function InitializeFireBaseMessaging() {
              messaging
                  .requestPermission()
                  .then(function () {
                      console.log("Notification Permission");
                      return messaging.getToken();
                  })
                  .then(function (token) {
                      console.log("Token : " + token);
                      sendToServer(token);
                  })
                  .catch(function (reason) {
                      console.log(reason)
                  })
          }
          messaging.onMessage(function (payload) {
              const notificationOption = {
                  body: payload.notification.body,
                  icon: payload.notification.icon,
  
              }
              if (Notification.permission == 'granted') {
                  var notification = new Notification(payload.notification.title, notificationOption);
                  notification.onclick = function (event) {
                      event.preventDefault();
                      window.open(payload.notification.click_action, "_blank");
                      notification.close();
                  }
              }
              console.log(payload);
          });
          messaging.onTokenRefresh(function () {
              messaging.getToken()
                  .then(function (newToken) {
                      console.log("New Token : " + newToken);
                      sendToServer(newToken);

                  })
                  .catch(function (reason) {
                      console.log(reason)
                  })
          })
  
          function sendToServer(token){
            $.ajax({
              url: "{% url 'staff_fcmtoken' %}",
              type: 'POST',
              data: {
                  token: token,
              }
          }).done(function (response) {
   
             
          }).fail(function (response) {
          })

          }
          
          InitializeFireBaseMessaging();
      </script>
{% endblock custom_js %}

main_app/templates/staff_template/staff_apply_leave.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

                    {% include "main_app/form_template.html" with messages=messages  form=form button_text="Apply For Leave"%}
                </div>
                <!-- /.card -->
<div class="card card-default">
    <div class="card-header"><h3 class="card-title"><b>Leave History</b></h3>
   <div class="table">

       <table class="table table-bordered table-hover">
           <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Date</th>
                <th>Message</th>
             <th>Status</th>
         </tr>
           </thead>
        {% for leave in leave_history %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{leave.date}}</td>
              <td>{{leave.message}}</td>
              <td>
                  
                  {% if leave.status == 0 %}
                  <span class="badge badge-warning">Pending</span>
                  {% elif leave.status == 1 %}
                  <span class="badge badge-success">Accepted</span>
                  
                    {% else %}
                    <span class="badge badge-danger">Rejected</span>
                    
                    {% endif %}
                    
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}