main_app/urls.py
from django.urls import path

from main_app.EditResultView import EditResultView

from . import hod_views, staff_views, booking_views, views

urlpatterns = [
    path("", views.landing_page, name="landing_page"),
    path("login/", views.login_page, name="login_page"),
    path("get_trips", views.get_trips, name='get_trips'),
    path("firebase-messaging-sw.js", views.showFirebaseJS, name='showFirebaseJS'),
    path("doLogin/", views.doLogin, name='user_login'),
    path("logout_user/", views.logout_user, name='user_logout'),
    path("admin/home/", hod_views.admin_home, name='admin_home'),
    path("staff/add", hod_views.add_staff, name='add_staff'),
    path("role/add", hod_views.add_role, name='add_role'),
    path("send_staff_notification/", hod_views.send_staff_notification,
         name='send_staff_notification'),
    path("add_Season/", hod_views.add_Season, name='add_Season'),
    path("admin_notify_staff", hod_views.admin_notify_staff,
         name='admin_notify_staff'),
    path("admin_view_profile", hod_views.admin_view_profile,
         name='admin_view_profile'),
    path("check_email_availability", hod_views.check_email_availability,
         name="check_email_availability"),
    path("Season/manage/", hod_views.manage_Season, name='manage_Season'),
    path("Season/edit/<int:Season_id>",
         hod_views.edit_Season, name='edit_Season'),
    path("booking/view/feedback/", hod_views.booking_feedback_message,
         name="booking_feedback_message",),
    path("staff/view/feedback/", hod_views.staff_feedback_message,
         name="staff_feedback_message",),
    path("staff/view/leave/", hod_views.view_staff_leave, name="view_staff_leave",),
    path("trips/fetch/", hod_views.get_admin_trips,
         name='get_admin_trips'),
    path("booking/add/", hod_views.add_booking, name='add_booking'),
    path("Car/add/", hod_views.add_Car, name='add_Car'),
    path("itinerary/add/", hod_views.add_itinerary, name='add_itinerary'),
    path("staff/manage/", hod_views.manage_staff, name='manage_staff'),
    path("booking/manage/", hod_views.manage_booking, name='manage_booking'),
    path("role/manage/", hod_views.manage_role, name='manage_role'),
    path("Car/manage/", hod_views.manage_Car, name='manage_Car'),
    path("itinerary/manage/", hod_views.manage_itinerary, name='manage_itinerary'),
    path("staff/edit/<int:staff_id>", hod_views.edit_staff, name='edit_staff'),
    path("staff/delete/<int:staff_id>",
         hod_views.delete_staff, name='delete_staff'),

    path("role/delete/<int:role_id>",
         hod_views.delete_role, name='delete_role'),

    path("Car/delete/<int:Car_id>",
         hod_views.delete_Car, name='delete_Car'),

    path("itinerary/delete/<int:itinerary_id>",
         hod_views.delete_itinerary, name='delete_itinerary'),

    path("Season/delete/<int:Season_id>",
         hod_views.delete_Season, name='delete_Season'),

    path("booking/delete/<int:booking_id>",
         hod_views.delete_booking, name='delete_booking'),
    path("booking/edit/<int:booking_id>",
         hod_views.edit_booking, name='edit_booking'),
    path("role/edit/<int:role_id>",
         hod_views.edit_role, name='edit_role'),
    path("itinerary/edit/<int:itinerary_id>",
         hod_views.edit_itinerary, name='edit_itinerary'),
    path("Car/edit/<int:Car_id>",
         hod_views.edit_Car, name='edit_Car'),




    # Staff
    path("staff/home/", staff_views.staff_home, name='staff_home'),
    path("staff/apply/leave/", staff_views.staff_apply_leave,
         name='staff_apply_leave'),
    path("staff/feedback/", staff_views.staff_feedback, name='staff_feedback'),
    path("staff/view/profile/", staff_views.staff_view_profile,
         name='staff_view_profile'),
    path("staff/trips/take/", staff_views.staff_take_trips,
         name='staff_take_trips'),
    path("staff/trips/update/", staff_views.staff_update_trips,
         name='staff_update_trips'),
    path("staff/get_bookings/", staff_views.get_bookings, name='get_bookings'),
    path("staff/trips/fetch/", staff_views.get_booking_trips,
         name='get_booking_trips'),
    path("staff/trips/save/",
         staff_views.save_trips, name='save_trips'),
    path("staff/trips/update/",
         staff_views.update_trips, name='update_trips'),
    path("staff/fcmtoken/", staff_views.staff_fcmtoken, name='staff_fcmtoken'),
    path("staff/view/notification/", staff_views.staff_view_notification,
         name="staff_view_notification"),
    path("staff/result/add/", staff_views.staff_add_result, name='staff_add_result'),
    path("staff/result/edit/", EditResultView.as_view(),
         name='edit_booking_result'),
    path('staff/result/fetch/', staff_views.fetch_booking_result,
         name='fetch_booking_result'),


    # booking
    path("booking/home/", booking_views.booking_home, name='booking_home'),
    path("booking/view/trips/", booking_views.booking_view_trips,
         name='booking_view_trips'),
    path("booking/apply/leave/", booking_views.booking_apply_leave,
         name='booking_apply_leave'),
    path("booking/feedback/", booking_views.booking_feedback,
         name='booking_feedback'),
    path("booking/view/profile/", booking_views.booking_view_profile,
         name='booking_view_profile'),
    path("booking/fcmtoken/", booking_views.booking_fcmtoken,
         name='booking_fcmtoken'),
    path("booking/view/notification/", booking_views.booking_view_notification,
         name="booking_view_notification"),
    path('booking/view/result/', booking_views.booking_view_result,
         name='booking_view_result'),

]

namelok_software_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("", include('main_app.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main_app/models.py
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import UserManager
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db import models
from django.contrib.auth.models import AbstractUser, User
# from networkx import cartesian_product
# from .tests import get_default_season, get_default_car
# from main_app.forms import CarForm
from main_app.tests import get_default_car, get_default_season
from namelok_software_system import settings

from django.contrib.auth import get_user_model
class CustomUserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = CustomUser(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        assert extra_fields["is_staff"]
        assert extra_fields["is_superuser"]
        return self._create_user(email, password, **extra_fields)


class Season(models.Model):
    name = models.CharField(max_length=120)
    start_year = models.DateField()
    end_year = models.DateField()

   

    def __str__(self):
        return "From " + str(self.start_year) + " to " + str(self.end_year)


class CustomUser(AbstractUser):
    USER_TYPE = ((1, "HOD"), (2, "Staff"), (3, "booking"))
    GENDER = [("M", "Male"), ("F", "Female")]
    
    username = None  # Removed username, using email instead
    email = models.EmailField(unique=True)
    user_type = models.CharField(default=1, choices=USER_TYPE, max_length=1)
    gender = models.CharField(max_length=1, choices=GENDER, default='M')  # Set default to 'Male'
    profile_pic = models.ImageField()
    address = models.TextField()
    fcm_token = models.TextField(default="")  # For firebase notifications
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

    def __str__(self):
        return self.last_name + ", " + self.first_name



class Admin(models.Model):
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)



class Role(models.Model):
    name = models.CharField(max_length=120)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class booking(models.Model):
    admin = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.DO_NOTHING, null=True, blank=True)
    season = models.ForeignKey(Season, on_delete=models.DO_NOTHING, null=True, blank=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='bookings', default=None)

    def __str__(self):
       return f"{self.user.last_name}, {self.user.first_name}"

class Staff(models.Model):
    name = models.CharField(max_length=255, default='Default Name')
    role = models.ForeignKey(Role, on_delete=models.DO_NOTHING, null=True, blank=False)
    admin = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.admin.last_name + " " + self.admin.first_name


class Car(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=120)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Itinerary(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=120)
    description = models.CharField(max_length=500)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name
    

class Trips(models.Model):
    season = models.ForeignKey(Season, on_delete=models.DO_NOTHING)
    car = models.ForeignKey(Car, on_delete=models.DO_NOTHING)
    date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class tripsReport(models.Model):
    booking = models.ForeignKey(booking, on_delete=models.DO_NOTHING)
    trips = models.ForeignKey(Trips, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class LeaveReportbooking(models.Model):
    booking = models.ForeignKey(booking, on_delete=models.CASCADE)
    date = models.CharField(max_length=60)
    message = models.TextField()
    status = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class LeaveReportStaff(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    date = models.CharField(max_length=60)
    message = models.TextField()
    status = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Feedbackbooking(models.Model):
    booking = models.ForeignKey(booking, on_delete=models.CASCADE)
    feedback = models.TextField()
    reply = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class FeedbackStaff(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    feedback = models.TextField()
    reply = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class NotificationStaff(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Notificationbooking(models.Model):
    booking = models.ForeignKey(booking, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class bookingResult(models.Model):
    booking = models.ForeignKey(booking, on_delete=models.CASCADE)
    Car = models.ForeignKey(Car, on_delete=models.CASCADE)
    test = models.FloatField(default=0)
    exam = models.FloatField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        if instance.user_type == 1:
            Admin.objects.create(admin=instance)
        elif instance.user_type == 2:
            # Assuming each CustomUser can have one Staff instance associated with it
            # Check if the CustomUser instance has an associated Staff instance
            staff_instance, _ = Staff.objects.get_or_create(admin=instance)
            staff_instance.name = f"{instance.last_name}, {instance.first_name}"
            staff_instance.save()
        elif instance.user_type == 3:
            booking.objects.create(admin=instance)


@receiver(post_save, sender=CustomUser)
def save_user_profile(sender, instance, **kwargs):
    if instance.user_type == 1:
        instance.admin.save()
    elif instance.user_type == 2:
        # Assuming each CustomUser can have one Staff instance associated with it
        # Check if the CustomUser instance has an associated Staff instance
        staff_instance, created = Staff.objects.get_or_create(admin=instance)
        # Save the Staff instance
        staff_instance.save()
    elif instance.user_type == 3:
        instance.booking.save()

main_app/templates/hod_template/add_booking_template.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block custom_css %}
  <style>
      .invalid{
        font-style: italic;
        font-weight: bold;
        color: red;
      }
      .valid{
        font-style: italic;
        font-weight: bold;
        color: green;
      }
  </style>
{% endblock custom_css %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

                    {% include "main_app/form_template.html" with messages=messages  form=form button_text="Add booking"%}
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}
{% block custom_js %}
<script>
    function validateEmail(email) {
        const re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        return re.test(String(email).toLowerCase());
    }
    $(document).ready(function(){
        $("#id_email").keyup(function(){
            
            var email = $(this).val()
            if (validateEmail(email)){
            $.ajax({
                url: "{% url 'check_email_availability' %}",
                type: 'POST',
                data:{email:email}
            }).done(function(response){
                if (response == "True"){
                    $(".email_error").remove()
                    $("<span class='invalid email_error'>Email Address Already Exist</span>").insertAfter("#id_email");
                }
                else{
                    $(".email_error").remove()

                    $("<span class='valid email_error'>Email Address Available</span>").insertAfter("#id_email");
                }
            }).fail(function(response){
                $("<span class='alert alert-warning'>Server Could Not Process This</span>").insertAfter("#id_email");
            })
        }
        })
    });
</script>
{% endblock custom_js %}

main_app/templates/hod_template/add_itinerary_template.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

                    {% include "main_app/form_template.html" with messages=messages  form=form button_text="Add Itinerary"%}
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}

main_app/templates/hod_template/add_role_template.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

                    {% include "main_app/form_template.html" with messages=messages  form=form button_text="Add role"%}
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}

main_app/templates/hod_template/admin_view_attendance.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block custom_css %}
<style>
.trips_div_red{
    padding: 10px;
    background: #f44336;
    border: 3px solid white;
    text-align: center;
    color: #fff;
    border-radius: 30px;
    box-shadow: 1px 1px 1px grey;
    margin: 5px;
}
.trips_div_green{
    padding: 10px;
    background: #4CAF50;
    border: 3px solid white;
    text-align: center;
    color: #fff;
    border-radius: 30px;
    box-shadow: 1px 1px 1px grey;
    margin: 5px;
}
</style>
{% endblock custom_css %}
{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="card-body">



                        <div class="form-group">
                            <label>Car</label>
                            <select name="Car" class="form-control" id='Car'>
                                <option value="">----</option>
                                {% for Car in Cars  %}
                                <option value="{{Car.id}}">{{Car.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Season</label>
                            <select name="Season" class="form-control" id='Season'>
                                <option value="">----</option>
                                {% for Season in Season  %}
                                <option value="{{Season.id}}">{{Season}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group"><div  style="display: none;" class="alert alert-danger" id='error_trips'></div>
                                <div class="alert alert-success" id='success_trips' style="display: none;"></div>
                             <button type="button" id='fetch_trips' class="btn btn-success btn-block">Fetch trips</button>
                        </div>
                    <!-- /.card-body -->
                    
                        
                               
                            <div class="form-group" style="display: none;" id="trips_block">
                            <div class="form-group">
                                <label>trips Date</label>
                                <select name="trips_date" id='trips_date' class="form-control">
                               
                                </select>
                            </div>
                            <div class="form-group">
                                
                            <div id="fetch_booking_block" style="display: none;">
                                <button type="button" id='fetch_booking' class="btn btn-success btn-block">Fetch bookings</button>


                            </div>
                            <div id='booking_data' class="card-footer">

                            </div>
                        </div>
                    </div>  
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}


{% block custom_js %}
<script>
    $(document).ready(function () {
        $("#fetch_trips").click(function(){
            var Car = $("#Car").val()
            var Season = $("#Season").val()
            $("#booking_data").html("")

            if (Season.length < 1 || Car.length < 1){
                $("#error_trips").html("Kindly Choose Both Car and Season")
                $("#trips_block").hide()
                $("#error_trips").show()
                return false
            }
            $.ajax({
                url: "{% url 'get_trips' %}",
                type: 'POST',
                data:{
                    Car:Car,
                    Season:Season
                }
            
            }

            ).done(function(response){
                var json_data = JSON.parse(response)
                if (json_data.length > 0){

                    var html = "";
                    for (key in json_data){
                        html += "<option value='"+json_data[key]['id']+"'>"+json_data[key]['trips_date']+"</option>"
                    }
                    $("#trips_date").html(html)
                    $("#error_trips").hide()
                    $("#error_trips").html("")
                    $("#trips_block").show()  
                    $("#fetch_booking_block").show()
                }else{
                    $("#error_trips").html("No trips Date Found For Specified Data")
                    $("#error_trips").show()
                    $("#trips_date").html("")
                    $("#trips_block").hide()
                    $("#booking_data").html("")


                }
            }).fail(function(response){
                alert("Error While Fetching Data")
                $("#error_trips").html("")
                $("#error_trips").show()
                $("#trips_block").hide()
                $("#booking_data").html("")


            })
        })

        $("#fetch_booking").click(function () {
            var trips_date = $("#trips_date").val()
            var Season = $("#Season").val()
            var Car = $("#Car").val()
            $("#booking_data").html(null)
if (trips_date.length  == 0){
    alert("Please Choose A Date");
    $("#save_trips").hide()

    return false;
}
            $.ajax({
                url: "{% url 'get_admin_trips' %}",
                type: 'POST',
                data: {
                    trips_date_id:trips_date,
                    Season:Season,
                    Car:Car
                }
            }).done(function (response) {
                var json_data = JSON.parse(response)
                if (json_data.length < 1) {
                    alert("No data to display")

                } else {

                    var div_data = "<hr/><div class='form-group'></div><div class='form-group'> <label>booking trips</label><div class='row'>"

                    for (key in json_data) {
                            if (json_data[key]['status'] == 'True'){
                                div_data += "<div class='col-lg-3 trips_div_green'><b>"+ json_data[key]['name'] + "</b><br/>Present</div>" 
                            }else{
        
                                div_data += "<div class='col-lg-3 trips_div_red'><b>"+ json_data[key]['name'] + "</b><br/>Absent</div>"
                            }
                        }
                       // div_data += "<div class='col-lg-3'><div class='form-check custom-control custom-checkbox'><input type='checkbox' class='custom-control-input' " + (json_data[key]['status'] ? "checked='checked'" : "")+" name='booking_data[]' value=" + json_data[key]['id'] + " id='checkbox" + json_data[key]['id'] + "' /> <label for='checkbox" + json_data[key]['id'] + "' class='custom-control-label'>" + json_data[key]['name']  + (json_data[key]['status'] ? " [Present] " : " [Absent] ")+"</label></div> </div>"
                    div_data += "</div></div>"
                    $("#booking_data").html(div_data)
                }
            }).fail(function (response) {
                alert("Error in fetching bookings")
            })

        })
       
    })
</script>
{% endblock custom_js %}

main_app/templates/hod_template/edit_course_template.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

                    {% include "main_app/form_template.html" with messages=messages  form=form button_text="Edit role"%}
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}

main_app/templates/hod_template/edit_role_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ page_title }}</title>
</head>
<body>
    <h1>Edit Role</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
</body>
</html>

main_app/templates/hod_template/edit_season_template.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>
                    {% include "main_app/form_template.html" with messages=messages  form=form button_text="Update Season"%}
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}

main_app/templates/hod_template/edit_staff_template.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>
                    {% include "main_app/form_template.html" with messages=messages  form=form button_text="Update Staff"%}
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}

main_app/templates/hod_template/manage_itinerary_template.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead class="thead-dark">
                                <tr>
                                    <th>#</th>
                                    <th>Car</th>
                                    <th>description</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for itinerary in itinerary %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{itinerary.name}}</td>
                                    <td>{{itinerary.description}}</td>
                            
                                    <td>
                                        <a href="{% url 'edit_itinerary' itinerary.id %}" class="btn btn-info">Edit</a> -
                                        <a href="{% url 'delete_itinerary' itinerary.id %}" onclick="return confirm('Are you sure you want to delete this ?')" class="btn btn-danger">Delete</a> 

                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}